### PR TITLE
Added TypeScript typings

### LINKED ISSUE #2: Add TypeScript typings?
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/22839

It'd be great if these came packaged with the npm package instead of separately installable via `@types`.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #2.

I noticed the `copyStyles` prop is missing in README.md, so added it in to match the TS typings.

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
@rmariuzzo bump?

I can send a similar PR to DefinitelyTyped if you'd prefer the maintenance cost of these pushed there.

**Comment by rmariuzzo** [comment]
Thank you @JoshuaKGoldberg! Sorry for the long delay, will publish a new version soon.

**Comment by rmariuzzo** [comment]
Done! Released v0.0.5

**Comment by JoshuaKGoldberg** [comment]
Err @rmariuzzo I'm not seeing the `.d.ts` file in there.

Also, could you put a reference to it in `package.json` as `"types": "path/to/file"`?

**Comment by rmariuzzo** [comment]
Weird... will take a look shortly.

**Pull request merged**
